### ISSUE TITLE
Move entity between views

### ISSUE THREAD

**Issue by RossiNIT** [DigiLive/mushroom-strategy#107]
The library put windows and blinds in the same view or domain (named cover). I need to separate them, blinds is one "group" and windows is another "group"; so the views need to be separated, but also the section inside areas. I fount the way to create a new custom view (that I named blinds), but I can't remove the blind entities from cover and put into blinds, or move the entities between domains.
Is there a way to do this?

**Comment by AalianKhan** [comment]
The best way to achieve what you want is to hide the cover view and create a custom view for blinds, windows and covers. It is a bit of work but can be done if you want. I may consider adding separate views for them but currently, it's not on my radar.
