### ISSUE TITLE
Alarm chip/card

### ISSUE THREAD

**Issue by jayjakee** [DigiLive/mushroom-strategy#109]
I recently hooked a few of my automations to my home alarm but the status is not visible on the main page

Add an alarm chip with some sort of status Armed/Disarmed)

The only solution for now is to make my dashboard without the strategy

Not sure if it is suitable for everyone (but it might be the same as fan controls, which I don't have and I don't mind extra chips)
can I add it manually somehow?

**Comment by AalianKhan** [comment]
To add extra chips, you can use the `extra_chips` option, instructions can be found [here](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#chips)

**Comment by jayjakee** [comment]
completely forgot about this thread, i think i got it working like few days after the post

**Comment by derekpurdy** [comment]
I can't figure this out, can an example be provided? Thanks

**Comment by DigiLive** [comment]
> I can't figure this out, can an example be provided? Thanks

What have you tried so far?
There's an example in the link provided above, but there are many settings available.
Please show us your code.
