### ISSUE TITLE
Unable to delete certain entities / tags

### ISSUE THREAD

**Issue by hackintoshlover** [DigiLive/mushroom-strategy#113]
**Describe the bug**
Trying to delete few entities but not finding an option for the same.
Please refer picture below.
![Screenshot (352)](https://github.com/AalianKhan/mushroom-strategy/assets/40655406/fa924cf3-5a32-4b0d-9fb9-089c94ef0a7d)

Also how to delete  pages like the camera page, i don't see an option to do so.
![Screenshot (353)](https://github.com/AalianKhan/mushroom-strategy/assets/40655406/a1e49d62-57c3-49a4-9c67-c961708b5bd5)
![Screenshot (354)](https://github.com/AalianKhan/mushroom-strategy/assets/40655406/0b1fd774-51fe-41f6-a71f-fa00183d1472)

**Versions**
* Mushroom-Strategy: v1.0.1
* HACS: v1.33.0
* Mushroom: v3.2.3
* Home Assistant:
* Core
2023.11.3
Supervisor
2023.12.0
Operating System
11.1
Frontend
20231030.2

**To Reproduce**

Create a mushroom strategy dashboard.

**Comment by AalianKhan** [comment]
Hello,

It looks like you didn't install mini graph card. You can follow the instructions [here](https://github.com/AalianKhan/mushroom-strategy/wiki#prerequisites) to install them.

To hide a view, you can follow the [steps](https://github.com/AalianKhan/mushroom-strategy/wiki/Strategy-Options#view-options) listed here. 

For example:
```YAML
strategy:
  type: custom:mushroom-strategy
  options:
    views:
      camera:
        hidden: true
views: []
