### ISSUE TITLE
After editing the home screen using the visual editor, clicking on the room doesn't go to that room

### ISSUE THREAD

**Issue by clowgg** [DigiLive/mushroom-strategy#116]
**Describe the bug**
After editing the home screen using the visual editor, clicking on the room doesn't go to that room

**Versions**
* Mushroom-Strategy: 2.0
* HACS: 1.34.0
* Mushroom: 3.2.4
* Home Assistant: 2024.1.5

**To Reproduce**

1. Go to Home screen
2. Edit the Dashboard, take ownership, edit the home screen Area card stack.
3. Change the order of cards, save.
4. Click on a area/room - the view does not change. The URL does change, but the browser stays on the dashboard home page.

**Expected behavior**
The area/rooms click would change the browser view to that room as when the home screen area card stack is in its default order.

**Screenshots**
Changed order of card stack:
![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/cbee9cfc-5bcd-4ffe-ba44-c5fa1849f105)

**Additional context**
I have noticed that the areas/rooms become "UNNAMED VIEW" tabs across the top bar. When you click on these, the associated area/room opens up fine.

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/3e12c705-1525-4041-8335-32d134c427ea)

**Comment by DigiLive** [comment]
What exactly do you mean with "visual editor".
Only a "YAML editor" should be available.

**Comment by clowgg** [comment]
This one...

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/493eccb5-1174-461b-81b4-b40489d9920c)

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/2bceb92b-eb92-47a1-bafc-f329b676a6ee)

**Comment by clowgg** [comment]
Have I done something that wasn't supposed to be possible?

**Comment by DigiLive** [comment]
> Have I done something that wasn't supposed to be possible?

I'm not sure, but it seems to me your yaml configuration file isn't compatible anymore.
It should be something like https://github.com/AalianKhan/mushroom-strategy/wiki/Full-Example
and at least:

```yaml
strategy:
  type: custom:mushroom-strategy
views: []
```

I suspect both mushroom-strategy as well as the default hass-strategy are trying to setup the dashboards, based on the contents of the yaml file. This will lead to such errors.

**Comment by clowgg** [comment]
So what is the right way to edit the dashboard then?
When I have it displayed in the browser, and I click 3 dots - Edit dashboard, I get this:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/11434e6c-ee13-4c77-b0cf-4ee790da1b6d)

If I press Save, it goes back to the dashboard.
If I click the 3 dots, I get:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/3258c121-bc62-4690-90c6-cbafc2963333)

If I click Raw config editor, I get the basic starter yaml:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/22e12ff3-78b8-419f-8a11-da907cd8211f)

If I click Take control, I get:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/ee4d5e7a-2b3d-4c8e-808d-fef2cfe57f88)

which is what I did to get the visual editor view I showed in my previous comment. 

If this breaks the dashboard, how do you get to see the full yaml so you can change the order the rooms appear it, their icons, and the colours of the icons?

**Comment by DigiLive** [comment]
You don't take control.

If you do, both mushroom-strategy as well as Home Assistant are trying to setup the dashboards, which doesn't work.

mushroom-strategy generates the dashboard configuration on the fly, while Home Assistant will try to use the static configuration in the yaml file.

**Comment by clowgg** [comment]
Thank you for the update. 
I now understand the approach that I must take.

I have edited the yaml file correctly, and have success!! :)

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/30dbd589-8eae-42a6-9595-cafcf534e645)

**Comment by DigiLive** [comment]
I'm glad it works out for you. :)
