### ISSUE TITLE
home_view options are not working.

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/mushroom-strategy#119]
> ```yaml
> strategy:
>   type: custom:mushroom-strategy
>   options:
>     home_view:
>       hidden:
>         - greeting
> views: []
> ```

unfortunately this did not work either.

_Originally posted by @derekpurdy in https://github.com/AalianKhan/mushroom-strategy/issues/82#issuecomment-1910286580_

**Comment by clowgg** [comment]
I got it working:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/6a517798-cdd9-4ed5-87cf-0cf126a3f1e9)

![image](https://github.com/AalianKhan/mushroom-strategy/assets/145304547/15058e37-4131-4429-ac88-123f7f321be9)

**Comment by DigiLive** [comment]
@derekpurdy I've checked and it all seems fine to me.
Are you sure you're using v2.0.0 and don't have any caching issues?

**Comment by derekpurdy** [comment]
> @derekpurdy I've checked and it all seems fine to me. Are you sure you're using v2.0.0 and don't have any caching issues?

i tried it incognito, and it appears you're right.. it's updating now as I'm making changes.
