### ISSUE TITLE
Hide entities with state "unavailable"

### ISSUE THREAD

**Issue by adamminer** [DigiLive/mushroom-strategy#12]
**Is your feature request related to a problem? Please describe.**
I have devices that aren't always powered on for any amount of reasons.
As an example, I have a heated mattress pad that I use only in Winter.

**Describe the solution you'd like**
I'd like to have entities shown only on the dashboard only when the device is plugged in, rather than having to exclude all related entities (Power Level, duration, etc.) manually each winter.

**Describe alternatives you've considered**
N.A.

**Additional context**
Relates to #10

**Comment by Sooty70** [comment]
+1 from me - I have a similar use case with my Christmas/seasonal lights in the garden and house.

**Comment by DigiLive** [comment]
Can you please give commit d506630 of the main branch a try to see if the issue is still present?

**Comment by DigiLive** [comment]
I've created a [pre-release](https://github.com/AalianKhan/mushroom-strategy/releases/tag/1.0.0-alpha.1) which you could try.
@adamminer or @Sooty70 Any feedback would be appreciated.

Otherwise this issue will be closed for being fixed or stale.

**Comment by DigiLive** [comment]
Closed for being stale.

**Comment by jacauc** [comment]
Opened a similar issue than this stale issue from 3 years ago. Looks like it was never tested and closed as a result.




https://github.com/DigiLive/mushroom-strategy/issues/319
