### ISSUE TITLE
Climate view is missing since last 

### ISSUE THREAD

**Issue by Chartreusito** [DigiLive/mushroom-strategy#123]
**Describe the bug**
Climate view is missing

**Versions**
* Mushroom-Strategy:  v2.0.2
* HACS: 1.34.0
* Mushroom: v3.2.4
* Home Assistant: 2024.1.5

**To Reproduce**

1. Go to 'Home View'
2. No Climate view

**Expected behavior**
I'd like to see climate view as it used to be

**Screenshots**
![Screenshot 2024-01-27 at 17-22-59 Mushroom strategy – Home Assistant](https://github.com/AalianKhan/mushroom-strategy/assets/88147733/ccf80546-17ce-4262-aee8-ed3be839cbc7)

**Additional context**
I disabled all chip on HomeView cause i don't like someone to missclik and turn off everything by mistake.
My "switch" view is hidden in my config, but my climate is not. Even if i add it explicitely i don't have access to it anymore.
If i enable the climate chip and i long press the climate chip i don't have access to the climate view.

**Comment by DigiLive** [comment]
The climate view should still be available.
It requires at least one enabled and unhidden (by Home Assistant or the configuration) entity of the `climate` domain or the view won't be generated.

Maybe the script ran into an error, but I'll need to see the console output of your browser for that.

**Comment by Chartreusito** [comment]
Thanks, all my climate entities were indeed hidden as i'm using 2 dashboard right now and wanted to hide climate entities on the non mushroom dashboard
