### ISSUE TITLE
“ structuredClone is not defined” in Fully kiosk browser

### ISSUE THREAD

**Issue by lexcao1729** [DigiLive/mushroom-strategy#125]
**Describe the bug**

ReferenceError: structuredClone is not defined

It happens in Fully Kiosk browser on my Android pad.
![IMG_1335](https://github.com/AalianKhan/mushroom-strategy/assets/89396980/3e2f50aa-c4d2-4f9c-9bae-d0cb58c2ed3b)

**Comment by DigiLive** [comment]
Please fill in the details which are asked for in the bug template.

**Comment by DigiLive** [comment]
`structuredClone()` is removed from the current release.
Please update your installation.
