### ISSUE TITLE
Request: Get generated strategy output

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/mushroom-strategy#133]
### Discussed in https://github.com/AalianKhan/mushroom-strategy/discussions/89

<div type='discussions-op-text'>

<sup>Originally posted by **mazany** November 12, 2023</sup>
Hi. I really like this strategy as a quick showcase, but I would like to look at the generated YAML configuration to use it in my manual dashboards.

Is that possible somehow?

Thank you.</div>

**Comment by TheFelix93** [comment]
> ### Discussed in #89
> Originally posted by **mazany** November 12, 2023 Hi. I really like this strategy as a quick showcase, but I would like to look at the generated YAML configuration to use it in my manual dashboards.
> 
> Is that possible somehow?
> 
> Thank you.

1. Open your auto generated dashboard.
2. Click on the three dots right upper corner and select option edit dashboard.
   Now you should see the yaml code with the mushroom strategy statement and options.
3. From there again three dots in corner and press "take control".
4. Leave the "start with empty" off and confirm.

If you now get into the yaml editor of the dashboard again you see the the full hardcoded configuration that was generated before.
