### ISSUE TITLE
Error loading the view strategy:  Type Error: Cannot read properties of undefined (reading 'domains')

### ISSUE THREAD

**Issue by Manu6308** [DigiLive/mushroom-strategy#136]
I don't know how to solve that, I'm very new at this, thank you.

**Comment by DigiLive** [comment]
Follow the instructions at https://github.com/AalianKhan/mushroom-strategy/discussions/90

**Comment by Thepapy** [comment]
hey i have exactly the same :(

**Comment by DigiLive** [comment]
@Thepapy Did you follow the instructions at #90?
