### ISSUE TITLE
Auto import area/entity/user icons

### ISSUE THREAD

**Issue by TheSpaceGod** [DigiLive/mushroom-strategy#147]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Most of my areas/entities/users already have icons assigned to them in their various setting menus.  Would it be possible to import those existing icons and use them in the auto generated dashboard?

**Describe alternatives you've considered**
Manually adding icons.

**Additional context**
N/A

**Comment by soif** [comment]
I vote for it too, especially Area icons on the auto generated landing page.

-----

> While there, an option to have more than 2 columns of areas, would be great...

_(I've just seen that someone opened a [PR](https://github.com/AalianKhan/mushroom-strategy/pull/84) for the area colums count)_

Best regards,

**Comment by w531t4** [comment]
@TheSpaceGod @soif - Based on what i see, the entity icons and user icons are already imported.

**Comment by DigiLive** [comment]
> While there, an option to have more than 2 columns of areas, would be great...

Hold that thought, as I'm planning to change the layout from masonry to sections/grid system which could include defining the amount of columns.

**Comment by soif** [comment]
> @TheSpaceGod @soif - Based on what i see, the entity icons and user icons are already imported.

Sorry, I meant the AREA icons , in the custom:mushrooom-strategy. 
_As reported [here](https://github.com/AalianKhan/mushroom-strategy/pull/158)._
