### ISSUE TITLE
Error: Timeout waiting for strategy element ll-strategy-mushroom-strategy to be registered

### ISSUE THREAD

**Issue by sadiq81** [DigiLive/mushroom-strategy#15]
**Describe the bug**
No UI elements is presented, only an error message after a short loading period

**To Reproduce**
1. Install via HACS
2. Restart
3. Create dashboard 
4. Open dashboard 

**Expected behavior**
Dashboard is showing like in the video. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/1586725/233276178-ccf67a83-da9a-4bee-9a80-8de3124fd174.png" height="800">&<img src="https://user-images.githubusercontent.com/1586725/233276293-03367ff6-3c7c-44d5-90fc-b7d2f4999115.png" height="800">

**Additional context**
N/A

**Comment by DigiLive** [comment]
Is the library added to Home Assistant as a dashboard resource?

Add reference to mushroom-strategy.js in Dashboard. There's two way to do that:

- Using UI:
  Settings → Dashboards → More Options icon (3 dots) → Resources → Add Resource → 
  Set Url to `/hacsfiles/mushroom-strategy/mushroom-strategy.js`
  Set Resourcetype to `JavaScript-module`.

  Note: If you do not see the Resources menu, you will need to enable Advanced Mode in your User Profile

- Using YAML:
  Add following code to lovelace section.
```yaml
    resources:
        - url: /hacsfiles/mushroom-strategy/mushroom-strategy.js
          type: module
```

Use `/local/mushroom-strategy.js` as url if you followed the manual installation instructions.

Also clear the cache of you client.

**Comment by sadiq81** [comment]
Thank you very much, I thought it was handled during installation.

**Comment by DigiLive** [comment]
Your welcome, I'm glad it worked out for you.

I'll have to admit these instructions in the readme aren't very clear at the moment since they are mentioned under manual installation.

@AalianKhan Can you update the readme in PR #7 ?

**Comment by AalianKhan** [comment]
@sadiq81 
Did you happen to see a `Not loaded` header in HACS at all?
[example](https://hacs.xyz/docs/faq/status_not_loaded/)

**Comment by sadiq81** [comment]
I don't think so.

**Comment by AalianKhan** [comment]
I see, did you try reinstalling it?

**Comment by DigiLive** [comment]
I did a check myself by uninstalling the repository and installing it again.
The dashboard resources where updated both times.

Let's hope this was a one-time quirk of HACS.
But we can still add it to the readme as a hint.

**Comment by RichardPar** [comment]
Also having the issue... It worked a few times. Cleared caches - installed from HACS too many times..
It worked briefly - when I hid entities so they are not shown, hell broke lose. Even restoring the entities didnt bring it back

```Error loading the dashboard strategy:

    Error: Timeout waiting for strategy element ll-strategy-mushroom-strategy to be registered
```

```
strategy:
  type: custom:mushroom-strategy
views: []
```
![image](https://github.com/AalianKhan/mushroom-strategy/assets/1158641/6a1f476a-ef02-496e-97a9-17c1947a2aa9)
HACS shows its loaded

**Comment by DigiLive** [comment]
Any thoughts on this @AalianKhan ?

**Comment by AalianKhan** [comment]
This mainly happens when the resource isn't loaded. Instructions on how to explicitly declare the resource are [here](https://github.com/AalianKhan/mushroom-strategy/issues/15#issuecomment-1515864915)

@RichardPar Are you still having this issue?

**Comment by RichardPar** [comment]
yep...

I had it running once ... I have re-installed so many times I lost count.
I disappointingly gave up

Richard

**Comment by DigiLive** [comment]
I've created a [pre-release](https://github.com/AalianKhan/mushroom-strategy/releases/tag/1.0.0-alpha.1) which you could try.
@RichardPar Any feedback would be appreciated.

Otherwise this issue will be closed for being fixed or stale.

**Comment by RichardPar** [comment]
> 
Thanks!

This seems to work :D Now to play some more 


![image](https://github.com/AalianKhan/mushroom-strategy/assets/1158641/4e91c31c-217c-409a-b9c1-aa58398c3b9a)

**Comment by DigiLive** [comment]
Awesome.
Keep in mind it's still an alpha release, so it's not fully tested.
Closing this issue for now. Feel free to open any new issue when needed.
