### ISSUE TITLE
All cameras disappeared after enabling them in Homekit Bridge

### ISSUE THREAD

**Issue by clowgg** [DigiLive/mushroom-strategy#152]
**Describe the bug**
All my 10 cameras disappeared from the dashboard after I enabled them to be published by Homekit Bridge.

**Versions**
* Mushroom-Strategy: 2.1.0
* HACS: 2.0.1
* Mushroom: 4.0.8
* Home Assistant: 2024.10.4

**To Reproduce**

1. have cameras published in mushroom-strategy
2. enable Homekit Bridge integration
3. activate cameras as published accessories in Homekit
4. cameras still show up in lovelace dashboards - standard camera cards
5. see them disappear from the strategy dashboard

**Expected behavior**
Camera's still show up in strategy dashboard.

**Comment by DigiLive** [comment]
Any output in the console of the browser's developer tools (F12)?

**Comment by clowgg** [comment]
This is a copy of the Dev console after doing a Ctrl-F5 in Edge:

![image](https://github.com/user-attachments/assets/99b2233e-143a-4d3f-8001-4134dcdd5ab8)

**Comment by clowgg** [comment]
Do you want me to expand on any of those fields?

**Comment by clowgg** [comment]
I just noticed that one camera is still showing in the 'All Cameras' page:

![image](https://github.com/user-attachments/assets/35de8d6a-7f9c-4471-9dd6-3c54ee9d1250)

This one is a duplicate stream that I have NOT activated in Homekit.

**Comment by clowgg** [comment]
This Backdeck one is also showing on the main dash:

![image](https://github.com/user-attachments/assets/a4c733b3-c643-40b7-821f-0f65a35851c2)

**Comment by clowgg** [comment]
Found a way to fix the issue!
The Area setting for all cameras had been wiped.
Re adding the Area in the NVR integration entities makes them reappear in Strategy! :)

![image](https://github.com/user-attachments/assets/0829efa9-e671-4b72-80f3-863bae001287)

**Comment by DigiLive** [comment]
So this issue can be closed?

**Comment by clowgg** [comment]
Yes, it looks like it can.
