### ISSUE TITLE
A way to split the dashboard config file  

### ISSUE THREAD

**Issue by AlexisHutin** [DigiLive/mushroom-strategy#17]
Hello, 
First of all, thank you for your work ! 

So, I don't know if there is a way to do it, but, I'd like to split the dashboard config file in smaller pieces.
Like " !include: " in the configuration.yaml file.
Because, when you have to custom a bit your dashboard the file is unreadable.
I think, splitting files is more comfortable for maintenance or evolution of our dashboard :)

Thank you

**Comment by DigiLive** [comment]
I believe the `!include` directives aren't supported for yaml file of the dashboard configuration.
If I'm wrong, I'd like to hear about it.

For now, I'll leave this issue opened.
Maybe we can make up another method for splitting up the configuration, but it will always involve placing additional yaml files on your Home assistant device manually.
This might be out of scope of this plugin.

@AalianKhan What do you think?

**Comment by AalianKhan** [comment]
Currently, the Raw configuration editor from the UI doesn't support `!include`. However, you can add some lines to your `configuration.yaml` to add YAML dashboard which does support `!include`. See [docs)](https://www.home-assistant.io/dashboards/dashboards/#adding-more-dashboards-with-yaml)

**Comment by AlexisHutin** [comment]
Thank you for the answer :) 
I'll check the doc you linked me
