### ISSUE TITLE
Some cameras dont work - MSE source error: unsupported content type

### ISSUE THREAD

**Issue by TRusselo** [DigiLive/mushroom-strategy#18]
**Describe the bug**
My cameras (provided to HA via Blue Iris integration) do not work.

**To Reproduce**
Create Dashboard.
go to camera page
blueiris cameras have error :   mse: source 0 error: unsupported content-Type: application/vnd.apple.mpegurl
nest camera is OK

**Expected behavior**
see camera stream

**Screenshots**
![image](https://user-images.githubusercontent.com/1154815/235193092-578ac0a1-cedd-429b-8f8e-c96e96a4855a.png)

**Additional context**

**Comment by AalianKhan** [comment]
Although this should work, [web2rtc](https://github.com/AlexxIT/WebRTC#custom-card) doesn't support every integration and this might one of them. 

As a fix you can use [entity_config](https://github.com/AalianKhan/mushroom-strategy#entity-config) to define a card for the blue iris cameras.
