### ISSUE TITLE
Error Loading the Dashboard Strategy

### ISSUE THREAD

**Issue by FriedCheese2006** [DigiLive/mushroom-strategy#21]
**Describe the bug**
Installed via HACS along with the dependencies. Created a new dashboard. Dashboard works fine form Chrome on PC and Android but gives the error in the companion app.

**To Reproduce**
1. Add new dashboard
2. Open dashboard in the companion app

**Expected behavior**

**Screenshots**

![Screenshot_20230519-133231](https://github.com/AalianKhan/mushroom-strategy/assets/49689423/1fec435b-096c-485e-8fa8-63b5b53e482d)
![Screenshot_20230519-133253](https://github.com/AalianKhan/mushroom-strategy/assets/49689423/7b97fe3a-74b3-4988-b88c-c1b6e3ab7e8c)

**Additional context**

**Comment by FriedCheese2006** [comment]
It randomly started working.

**Comment by AalianKhan** [comment]
Clearing cache mitigates this issue. I will add it to wiki. Thanks 👍
