### ISSUE TITLE
Hide the default person cards

### ISSUE THREAD

**Issue by raddacle** [DigiLive/mushroom-strategy#23]
I'd like to remove the person cards from the home screen, though it doesn't seem that there is a way currently, is that right?

**Comment by AalianKhan** [comment]
Yes, you are correct. There is no way to hide the person cards.

I think the person cards add a bit of personalization and I personally do track my members just to see where they are at.

Can you give an argument to sway me?

**Comment by raddacle** [comment]
Well, I'm trying out this integration for the home assistant server at my family's home, and they use the home assistant app regularly. This integration would be incredible to reduce the amount of maintenance time I spend on their sever, though the person cards would a dealbreaker.  

Everyone in the family is uncomfortable that others family members can track their location through HA, though fortunately here, they aren't great with tech. So I've hidden the person entity cards and map tab, so that locations can still be used for automations. Technically they could still view locations if they knew where to look, but they don't and they haven't tried.

**Comment by DigiLive** [comment]
> Everyone in the family is uncomfortable that others family members can track their location through HA...

I'm not the code owner, but this makes sense to me.

Hiding (person) cards by configuration wouldn't be much of a hassle, I think. We could do it the same way as we hide/override the areas in the next release.

**Comment by Sooty70** [comment]
I would appreciate having the ability to exclude specific individuals from the persons card. 

Currently, the device tracker captures all our visitors, and simply hiding them is does not remove them - disabling them is the only way to exclude them from the view.  This however leads to complications with some of my automations, rendering them dysfunctional.

**Comment by AalianKhan** [comment]
[Fixed](https://github.com/AalianKhan/mushroom-strategy/commit/5bded12e703c1502631aa6eb024d3e804a446c91)
