### ISSUE TITLE
Hide view if no device is configured

### ISSUE THREAD

**Issue by tobiasff3200** [DigiLive/mushroom-strategy#24]
**Is your feature request related to a problem? Please describe.**
I really like this integration, but I do not have smart covers, fans, or cameras. Therefore, these views are not useful for me.

**Describe the solution you'd like**
It would be great if the overview views are hidden if no device is configured in HA. For example if no cameras are integrated the camera view is hidden.

**Describe alternatives you've considered**
I could manually configure the views to be disabled but if I add a camera later, it would not show up automatically in the dashboard.

**Comment by DigiLive** [comment]
I guess it makes kinda sense.

On the other hand, if you have to take actions to add a camera (or something) already, it wouldn't be much of a hassle to include the view either.

It's under consideration.

**Comment by tobiasff3200** [comment]
Yes you are right it is totally 'I am too lazy to do it' :sweat_smile:    
But if it is no big deal to implement it would be quite convenient.
