### ISSUE TITLE
Getting error "Error loading the view strategy:  TypeError: Cannot read properties of undefined (reading 'attributes')" when clicking on 6 areas out of 14

### ISSUE THREAD

**Issue by SaintTDI** [DigiLive/mushroom-strategy#25]
Hi,

It's my first issue that i'm opening on github, so I'm sorry if I'm doing something wrong :) 

I just installed mushroom-strategy, really cool! But I have an issue when clicking on 6 different Rooms out of the total of 14. The error is:

Error loading the view strategy:

TypeError: Cannot read properties of undefined (reading 'attributes')

![image](https://github.com/AalianKhan/mushroom-strategy/assets/23402327/01741c40-0e7b-44cd-9c8d-309092ec69e3)

Other Rooms don't have any issues. I thought it was the Aqara door sensor, but actually a Room that works use one of them.

EDIT:

Ok, I think the shutter is the issue, because only rooms with shutter have this issue. Deleting the Room association of one shutter, the room opens correctly:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/23402327/d5a1f85a-f025-4e5d-ab27-8e121c4c0b9b)

But opening the page of the shutters everything works:

![image](https://github.com/AalianKhan/mushroom-strategy/assets/23402327/26986dd6-7b3b-4b28-bb50-c2facd579257)

I use the Shelly Pro 2 PM for the shutters and these are the attributes:

current_position: 100
device_class: shutter
friendly_name: Tapparella Camera
supported_features: 15

Can anyone help please?

Thanks! 
Stefano

**Comment by DigiLive** [comment]
Can you please give commit d506630 of the main branch a try to see if the issue is still present?

**Comment by SaintTDI** [comment]
> Can you please give commit [d506630](https://github.com/AalianKhan/mushroom-strategy/commit/d5066303f385dc9499b002e913a6987b4c364fe0) of the main branch a try to see if the issue is still present?

Sorry, can you explain me how to do it? I'm new with github. Thanks!

**Comment by DigiLive** [comment]
1. Backup the contents of directory `/config/www/community`.
2. Rename/Remove the current files in above directory.
3. Download and place file https://github.com/AalianKhan/mushroom-strategy/blob/d5066303f385dc9499b002e913a6987b4c364fe0/dist/mushroom-strategy.js in above directory.
4. Refresh your browser's cache.

**Comment by DigiLive** [comment]
I've created a [pre-release](https://github.com/AalianKhan/mushroom-strategy/releases/tag/1.0.0-alpha.1) which you could try.
@SaintTDI Any feedback would be appreciated.

Otherwise this issue will be closed for being fixed or stale.

**Comment by DigiLive** [comment]
Closed for being stale.
