### ISSUE TITLE
Error loading dashboard

### ISSUE THREAD

**Issue by dualtronic** [DigiLive/mushroom-strategy#34]
This error is produced when trying to view the dashboard:
![image](https://github.com/AalianKhan/mushroom-strategy/assets/15826388/54d74c54-a980-4a32-b1f3-edfde0369c4c)

**To Reproduce**
Follow directions as stated including adding the extra devices from HACS. I am using Edge (chrome) and made sure to clear the cache as required.

Here is my dashboard configuration: 
![image](https://github.com/AalianKhan/mushroom-strategy/assets/15826388/6026e29f-13a1-46df-b1f1-c301af7b04d7)

Version info below:
![image](https://github.com/AalianKhan/mushroom-strategy/assets/15826388/cc9f6f96-d966-44da-a0e3-eed172733f0c)

**Comment by DigiLive** [comment]
@jlabataille See #15
