### ISSUE TITLE
unable to get card_options to work

### ISSUE THREAD

**Issue by hmatos-rogers** [DigiLive/mushroom-strategy#40]
Hi,
Great job on the strategy, I'm trying to use it for a wall tablet implementation and it's saving me quite a bit of time.

I'm having difficulty implementing the yaml below, specifically the "card_options". I'm trying to hide an entity card from one the areas in my dashboard.  Basically, nothing happens, the entity is still shown.

[issue.txt](https://github.com/AalianKhan/mushroom-strategy/files/12384337/issue.txt)

**Comment by AalianKhan** [comment]
Hello, 
It is working on my end with the alpha release. 
Can you try it with another entity id?

Also make sure you've installed the latest alpha release.

**Comment by hmatos-rogers** [comment]
Good morning,

Interesting, I thought I was on that version, apparently not.  I installed alpha 2 and it works.

Thank you very much for your help!
