### ISSUE TITLE
mini-graph-card the entity option was removed

### ISSUE THREAD

**Issue by floco** [DigiLive/mushroom-strategy#42]
**Describe the bug**  
mini-graph-card shows the entity option was removed

**Versions**  
* Mushroom-Strategy: 1.0.0-alpha.2
* HACS: 1.32.1
* Mushroom: v3.0.5
* Home Assistant: 2023.8.3
* Mini graph card: v0.11.0

**To Reproduce**  
1. Go to one room with a mini-graph-card
2. See error

**Expected behavior**  
graph displayed

**Screenshots**  
![image](https://github.com/AalianKhan/mushroom-strategy/assets/33659/86d43c75-7bef-4fe3-9ea6-43a1ca576571)

**Additional context**  
Happening with minimal config too
```
strategy:
  type: custom:mushroom-strategy
views: []
```

**Comment by floco** [comment]
Not sure where the extra "entity:" comes from. Couldn't find how to remove it in the strategy code.
However I removed the code generating the error in the mini-graph-card and that worked.

**Comment by DigiLive** [comment]
This error message is actually removed from mini-graph-card since v0.11.0, so shouldn't be reported in the console anymore.

It was last seen in release v0.10.0 of mini-graph-card. Maybe you've had a caching issue?

**Comment by floco** [comment]
Thanks @DigiLive, great catch, you were right. 
I removed mini-graph-card entirely, cleared everything. And now working perfectly.
Thanks again for your help :-)
