### ISSUE TITLE
Add option to hide all entities of a device

### ISSUE THREAD

**Issue by ajagnanan** [DigiLive/mushroom-strategy#48]
**Is your feature request related to a problem? Please describe.**
Enhance the feature https://github.com/AalianKhan/mushroom-strategy/issues/10 with a way to specify names via Regex

**Describe the solution you'd like**
This setting can be an option on the `entity_config` that hides entities based on a Regex

**Describe alternatives you've considered**
The alternate is to specify each and every entity that must be hidden via an individual `entity_config`

**Additional context**
Originated from https://github.com/AalianKhan/mushroom-strategy/issues/10

**Comment by AalianKhan** [comment]
The Regex seems very situational, not everyone names their entities structurally. We may be able to add an option to hide specific entities linked to a device.

Would that work better for you?

**Comment by ajagnanan** [comment]
Yea that would be good too. That's better if its possible to hide the device.

**Comment by damianosullivan** [comment]
Would it be possible to auto hide types of entity? I would like to hide all my batteries for example.
