### ISSUE TITLE
Id of weather entity is hardcoded.

### ISSUE THREAD

**Issue by DigiLive** [DigiLive/mushroom-strategy#5]
https://github.com/AalianKhan/mushroom-strategy/blob/51e0c7ea2549cfa86bef5617dfc0acd5ff3ecf67/dist/mushroom-strategy.js#L354

The id of the weather entity is hard-coded, making the weather chip (and mushroom js) fail if a user's entity id differs from it.

Possible solution:
```js
    const weatherEntity = entities.find(entity => entity.entity_id.startsWith("weather."))
    if (weatherEntity !== undefined) {
      chips.push
      (
          {
            type: "weather",
            entity: weatherEntity.entity_id,
            show_temperature: true,
            show_conditions: true
          },
      )
    }
```

Pros:
- No faulty weather chip in the DOM.
- No flooding of errors in the console.

Cons:
- Still depends on an entity id which might be different for other users (`weather.forecast_home` vs `forecast.home`.
- Binds the chip to the first weather entity found. (You could get all weather entities with a filter and create a chip for each entity.)

It's probably best to let the user configure which entity ids to use.

**Comment by AalianKhan** [comment]
Thanks for raising this issue.
I made the weather component static because the met.no integration is already pre-installed in home assistant. 

Since there is an an `extra_chips` option where users can add their own chips, I guess we can remove the weather chip all together and set if users want it they can easily add it. 

I still do like the idea of their being a weather chip by default tho.

**Comment by DigiLive** [comment]
I use the met integration also, but for some reason which I can't remember, I had to change the id some time ago.

I also like the idea of having such a chip by default, but it should only be added to the dashboard if the entity id exists. It raises a lot of errors if it doesn't. So a check is required anyway.

Considering the auto-dashboard feature...
IMHO, if including the chip by default, it's entity id should be configurable and fallback to the default id, if not set to something else.

In addition:

- I think you should check if the entity isn't disabled also.
  E.g. `weatherEntity = entities.find(entity => entity.entity_id.startsWith("weather.") && entity.disabled_by === null)`

- A disabled hourly forecast entity exists by default also. If using the `startsWith()` method, it might find this one before the daily forecast entity.

**Comment by AalianKhan** [comment]
Hey,
I added another field under chips for `weather_entity` that takes an entity_id for the weather card.
if weather_entity is not present then I used your code to find a weather entity and push the weather card if it is present. 
#6 
Can you test it with your setup?

When I was coding this I realized that I can maybe check if the weather entity is hidden or not. This way there shouldn't be a need to edit the YAML. The only downside is that it will require a unique_id. Although I didn't find any weather entity yet that doesn't use config flow for configuration, I still added the option just in case there is an integration that strictly uses configuration.yaml.

BTW thank you a lot for your very well-written feedback 👍

**Comment by DigiLive** [comment]
It looks like all is ok.
Thank you very much.

I've left a comment in the PR which hopefully leads to some level of collaboration.
