### ISSUE TITLE
2 Title cards in pre-built views

### ISSUE THREAD

**Issue by AalianKhan** [DigiLive/mushroom-strategy#56]
**Describe the bug**  
There are 2 title cards for the prebuilt views

**To Reproduce**  
1. Go to 'any pre-built view'
2. See error

**Expected behavior**  
1 title card to be shown

**Screenshots**  
![image](https://github.com/AalianKhan/mushroom-strategy/assets/39784853/71a0b6af-5fcb-4aa8-ba1b-b416ab2a6b4a)

**Additional context**

**Comment by AalianKhan** [comment]
@DigiLive I can't seem to find out why is this happening. Mind taking a look

**Comment by cdmicacc** [comment]
Hello! It looks like this fix should be in v1.0.0, but I just upgraded to v1.0.0 (from 1.0.0-alpha-2) and I am now seeing two title cards on the pre-built views (I did _not_ see two title cards in alpha-2).

<img width="519" alt="image" src="https://github.com/AalianKhan/mushroom-strategy/assets/431068/513eb00f-8416-4f85-8f57-87a3fb9af297">

**Comment by AalianKhan** [comment]
That's odd, can you check v1.0.1? try clearing the cache or use incognito mode.

**Comment by cdmicacc** [comment]
Unfortunately, I can't tell as that version doesn't work for me. I get a spinner followed by 

> Error loading the dashboard strategy:
> 
>     Error: Timeout waiting for strategy element ll-strategy-mushroom-strategy to be registered

(Tried reinstalling from scratch, and tried going back to the default configuration)

If it helps, I am using Mushroom 3.1.0, mini-graph-card 0.11.0, and the current version of HomeAssistant:

> Home Assistant 2023.9.3 
> Supervisor 2023.09.2
> Operating System 10.5
> Frontend 20230911.0 - latest

**Comment by AalianKhan** [comment]
> Error loading the dashboard strategy:
> 
> Error: Timeout waiting for strategy element ll-strategy-mushroom-strategy to be registered

This error usually pops up when the component hasn't been installed properly and cache hasn't been cleared. 
Can you confirm with me that you cleared the cache? Using incognito automatically rebuilds the cache from scratch so that is another tool you can use to see if it's working properly.

**Comment by cdmicacc** [comment]
Ah, good to know, thanks.  Yes, clearing the browser cache fixed that second issue, and updating to 1.0.1 seems to have fixed the two-title-cards issue.
