### ISSUE TITLE
Error loading the dashboard strategy

### ISSUE THREAD

**Issue by ductu3590** [DigiLive/mushroom-strategy#74]
I I have successfully installed and use the control panel via iPhone very well. The problem is when I have 1 more Android screen but when running mushroom strategy it gets an error like this image. Other regular Lovelace can still be loaded on this android screen 
![image](https://github.com/AalianKhan/mushroom-strategy/assets/97110519/1c3fde72-077d-49da-9ede-a3267161c2ae)
**Versions**  
* Mushroom-Strategy:
* HACS:
* Mushroom:
* Home Assistant:

**To Reproduce**  

**Expected behavior**  

**Screenshots**  

**Additional context**

**Comment by DigiLive** [comment]
https://github.com/AalianKhan/mushroom-strategy/issues/15#issuecomment-1515864915
