### ISSUE TITLE
Error loading the dashboard strategy (is back)

### ISSUE THREAD

**Issue by D-Jeffrey** [DigiLive/mushroom-strategy#88]
Standard default Mushroom-Strategy Config generated the error: 
```
Error loading the dashboard strategy:

Error: Timeout waiting for strategy element ll-strategy-dashboard-mushroom-strategy to be registered
```

```
strategy:
  type: custom:mushroom-strategy
views: []
```

Same error on iPhone and desktop using different browsers (Chrome, Edge).  

**Versions**  
* Mushroom-Strategy: v1.0.1 (but it is not listed in the code so that is just from the link)
* HACS: 1.33.0
* Mushroom: v3.2.2? 
* Home Assistant: 2023.11.1
* Frontend: 20231030.1

**To Reproduce**  
1. Go to 'Home Assistant.'
2. Click on 'Mushroom-Strategy' dashboard link
3. See error

**Expected behavior**  
The nested dashboard that did work before but stopped working in recent time.

**Additional context** 
- It has worked for me in the past, but I'm not sure the last time I checked it. 
- I have cleared the browser cache(s)
- The module is registered 
![image](https://github.com/AalianKhan/mushroom-strategy/assets/44452180/712cd127-e47d-4614-9712-83c0ecce6a65)

Could it be related to the number of devices - I have 65?

**Comment by AalianKhan** [comment]
Clearing the cache usually clears this issue. 

Do you know if anything else on your HA instance changed since the last time it was working?

**Comment by D-Jeffrey** [comment]
I checked to see if there was something in the previous closed issues. 

I check the Dev Console in the browser:
```
:8123/hacsfiles/mushroom-strategy/Helper:1 
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/hacsfiles/mushroom-strategy/cards/SensorCard:1 
        Failed to load resource: the server responded with a status of 404 (Not Found)
:8123/hacsfiles/mushroom-strategy/cards/TitleCard:1 
        Failed to load resource: the server responded with a status of 404 (Not Found)
get-strategy.ts:118  Error: Timeout waiting for strategy element ll-strategy-dashboard-mushroom-strategy to be registered
    at get-strategy.ts:66:11
    at async o (get-strategy.ts:88:11)
    at async Object.saveConfig (ha-panel-lovelace.ts:361:23)
    at async HTMLElement.value (hui-editor.ts:284:5)
```

I check the contents of he directory and the .gz looks to be corrupted.
```
[core-ssh mushroom-strategy]$ pwd
/root/homeassistant/www/community/mushroom-strategy
[core-ssh mushroom-strategy]$
[core-ssh mushroom-strategy]$ ls -l
total 16
-rw-r--r--    1 root     root          8424 Sep 30 11:58 mushroom-strategy.js
-rw-r--r--    1 root     root          2315 Sep 30 11:58 mushroom-strategy.js.gz
```

I went to HACS -> Frontend -> click on 'Auto generating Mushroom dashboard strategy' -> click on ... and selected Redownload.

```
[core-ssh mushroom-strategy]$ ls -l
total 36
-rw-r--r--    1 root     root         26472 Nov 11 16:30 mushroom-strategy.js
-rw-r--r--    1 root     root          6271 Nov 11 16:30 mushroom-strategy.js.gz
```
That Fixed it... really weird.

All good now, maybe add that to the Wiki too.

**Comment by DigiLive** [comment]
I've added some help in the Q&A of the discussions: #90
