### ISSUE TITLE
Can not load dashboard

### ISSUE THREAD

**Issue by Audio-Lefty** [DigiLive/mushroom-strategy#95]
**Describe the bug**  
When trying to get started get following message.
Error: Timeout waiting for strategy element ll-strategy-dashboard-mushroom-strategy to be registered

**Versions**  
* Mushroom-Strategy: 1.0.1
* HACS: Core  2023.11.2
   Supervisor      2023.11.3
   Operating System   11.1
   Frontend    20231030
* Mushroom: 3.2.2
* Home Assistant: 

**To Reproduce**  
Add text to empty dashboard vi raw configuration editor
```yaml
strategy:
  type: custom:mushroom-strategy
views: []
```

**Expected behavior**  
Dashboard to generate

**Screenshots**  

**Additional context**  
Tried to delete and reinstall

**Comment by DigiLive** [comment]
#90

**Comment by Audio-Lefty** [comment]
Hi,

Prior to reporting I had done everything in #90.

Also deleted to and reinstalled. Restarted and reboooted HA.

**Comment by DigiLive** [comment]
Ok, then please upload your diagnostics file of HACS.
See https://hacs.xyz/docs/basic/diagnostics/

**Comment by Audio-Lefty** [comment]
Mushroom Dashboard decided to appear.
Will leave things there for now. 
Not sure what I did right.
